[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Redirection principale pour forcer le HTTPS et le domaine sans www
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.renoconnect.fr/*"
  to = "https://renoconnect.fr/:splat"
  status = 301
  force = true

# Redirection pour l'API des fonctions Netlify
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirection SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes de sécurité et de cache
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "interest-cohort=()"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache pour les ressources statiques
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''
    Content-Type = "image/webp"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = '''
    public,
    max-age=0,
    must-revalidate'''